// Listens: 'docs:ready'

const ExportModule = {

  init() {
    EventBus.on('docs:ready', ({ docs, analyzed }) => this._enable(docs, analyzed));
  },

  _enable(docs, analyzed) {
    setModuleStatus('export', 'running');

    // List of all supported formats. Ensure these IDs exist in index.html as export-md, export-pdf, etc.
    const formats = ['md', 'html', 'json', 'txt', 'pdf'];
    
    formats.forEach(fmt => {
      const btn = document.getElementById(`export-${fmt}`);
      
      if (btn) {
        // Remove disabled state
        btn.classList.remove('disabled');

        // Clone to clear any old stuck event listeners
        const freshBtn = btn.cloneNode(true);
        btn.parentNode.replaceChild(freshBtn, btn);

        freshBtn.addEventListener('click', () => {
          this._export(fmt, docs, analyzed);
        });
      }
    });

    // Handle the Copy to Clipboard button
    const copyBtn = document.getElementById('copy-btn');
    if (copyBtn) {
      copyBtn.classList.remove('hidden');
      const freshCopy = copyBtn.cloneNode(true);
      copyBtn.parentNode.replaceChild(freshCopy, copyBtn);
      freshCopy.addEventListener('click', () => this._copyToClipboard(docs));
    }

    const exportMeta = document.getElementById('export-meta');
    if (exportMeta) exportMeta.textContent = '5 formats ready to download';
    
    setModuleStatus('export', 'done');
  },

  _export(format, docs, analyzed) {
    const filename = `documentation-${Date.now()}`;

    switch (format) {
      case 'md':   this._exportMarkdown(docs, filename); break;
      case 'html': this._exportHTML(docs, analyzed, filename); break;
      case 'json': this._exportJSON(docs, analyzed, filename); break;
      case 'txt':  this._exportText(docs, filename); break;
      case 'pdf':  this._exportPDF(docs, analyzed, filename); break;
    }

    // Only show the standard toast for non-pdf (PDF has its own success handler)
    if (format !== 'pdf') {
        showToast(`Exported as .${format.toUpperCase()}`, 'success');
    }
  },

  // --- PDF EXPORT ---
  _exportPDF(docs, analyzed, filename) {
    if (typeof html2pdf === 'undefined') {
        showToast('Error: PDF library not loaded', 'error');
        return;
    }

    showToast('Generating PDF...', 'info');

    const element = document.createElement('div');
    element.innerHTML = `
      <div style="font-family: sans-serif; padding: 40px; color: #1e293b;">
        <div style="border-bottom: 2px solid #3B82F6; padding-bottom: 10px; margin-bottom: 20px;">
          <h1 style="margin: 0; color: #1e293b; font-size: 28px;">Technical Documentation</h1>
          <p style="margin: 5px 0 0 0; color: #64748b;">Language: ${analyzed.language} | Total Lines: ${analyzed.totalLines}</p>
        </div>
        <div style="line-height: 1.7; font-size: 14px;">
          ${this._mdToHTML(docs)}
        </div>
        <div style="margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 10px; text-align: center; color: #94a3b8; font-size: 11px;">
          Generated by DocAI - ${new Date().toLocaleDateString()}
        </div>
      </div>
    `;

    const opt = {
      margin: 0.5,
      filename: `${filename}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(element).save().then(() => {
        showToast('PDF Exported!', 'success');
    });
  },

  _exportMarkdown(docs, filename) {
    if (typeof downloadFile === 'function') {
      downloadFile(docs, `${filename}.md`, 'text/markdown');
    }
  },

  _exportHTML(docs, analyzed, filename) {
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Documentation</title>
        <style>
          body { font-family: sans-serif; line-height: 1.6; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #333; }
          pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }
          code { background: #eee; padding: 2px 5px; border-radius: 3px; font-family: monospace; }
          h1 { color: #2563eb; }
          h2 { color: #3b82f6; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        </style>
      </head>
      <body>
        ${this._mdToHTML(docs)}
      </body>
      </html>
    `;
    if (typeof downloadFile === 'function') {
      downloadFile(htmlContent, `${filename}.html`, 'text/html');
    }
  },

  _exportJSON(docs, analyzed, filename) {
    const data = {
      meta: {
        generatedAt: new Date().toISOString(),
        language: analyzed.language,
        stats: { lines: analyzed.totalLines, functions: analyzed.functions.length }
      },
      content: docs
    };
    if (typeof downloadFile === 'function') {
      downloadFile(JSON.stringify(data, null, 2), `${filename}.json`, 'application/json');
    }
  },

  _exportText(docs, filename) {
    // Basic markdown strip
    const plainText = docs
      .replace(/#{1,6}\s/g, '')
      .replace(/\*\*([^*]+)\*\*/g, '$1')
      .replace(/`([^`]+)`/g, '$1');
    if (typeof downloadFile === 'function') {
      downloadFile(plainText, `${filename}.txt`, 'text/plain');
    }
  },

  async _copyToClipboard(docs) {
    try {
      await navigator.clipboard.writeText(docs);
      showToast('Copied to clipboard', 'success');
    } catch (err) {
      showToast('Failed to copy', 'error');
    }
  },

  // Helper to convert the AI Markdown into clean HTML for PDF/HTML exports
  _mdToHTML(md) {
    if (!md) return "";
    return md
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/```[\w]*\n([\s\S]*?)```/gm, '<pre><code>$1</code></pre>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/^(?!<)(.+)$/gm, '<p>$1</p>')
      .replace(/<p><\/p>/g, '');
  }
};

ExportModule.init();